// <auto-generated />
using System;
using Booking.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Booking.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241021155319_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Booking.DataAccess.Models.Table", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("Booking.DataAccess.Models.Table", b =>
                {
                    b.OwnsMany("Booking.DataAccess.Models.Booking", "Bookings", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("DateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<decimal>("Duration")
                                .HasPrecision(3, 1)
                                .HasColumnType("numeric(3,1)");

                            b1.Property<int>("NoOfPersons")
                                .HasColumnType("integer");

                            b1.Property<Guid>("TableId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("TableId");

                            b1.ToTable("Booking");

                            b1.WithOwner()
                                .HasForeignKey("TableId");

                            b1.OwnsOne("Booking.DataAccess.Models.Contact", "Contact", b2 =>
                                {
                                    b2.Property<Guid>("BookingId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Email")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)");

                                    b2.Property<string>("PhoneNumber")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)");

                                    b2.HasKey("BookingId");

                                    b2.ToTable("Booking");

                                    b2.WithOwner()
                                        .HasForeignKey("BookingId");
                                });

                            b1.Navigation("Contact")
                                .IsRequired();
                        });

                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
